name: bh_demo
dependencies:
- decorator=4.0.10=py27_0
- future=0.15.2=py27_0
- lxml=3.6.0=py27_0
- mkl=11.3.3=0
- networkx=1.11=py27_0
- nose=1.3.7=py27_1
- numpy=1.11.0=py27_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- pip=8.1.2=py27_0
- psutil=2.2.1=py27_0
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- readline=6.2=2
- requests=2.10.0=py27_0
- scipy=0.17.1=np111py27_0
- setuptools=23.0.0=py27_0
- simplejson=3.8.2=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traits=4.5.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - funcsigs==1.0.2
  - html5lib==0.9999999
  - isodate==0.5.4
  - keepalive==0.5
  - mock==2.0.0
  - nibabel==2.0.2
  - nipype==0.12.0
  - pbr==1.10.0
  - prov==1.4.0
  - pyparsing==2.1.5
  - rdflib==4.2.1
  - sparqlwrapper==1.7.6
  - xvfbwrapper==0.2.8

